name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
            
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    
    - name: Update version
      run: sed -i 's/CACHE_VERSION_VALUE/${{ github.run_id }}/g' src/VladislavAntonyuk/wwwroot/service-worker.published.js

    - name: Change base url
      run: sed -i 's/{BASE_URL}/https:\/\/vladislavantonyuk.github.io/g' src/VladislavAntonyuk/wwwroot/index.html
      
    - name: Publish .NET Project
      run: dotnet publish src/VladislavAntonyuk/VladislavAntonyuk.csproj -c Release -p:GHPages=true -p:GHPagesBase="/" -o release --nologo
      
    - name: Change constants
      run: sed -i 's/public const string BaseUrl = "\/";/public const string BaseUrl = "https:\/\/vladislavantonyuk.github.io\/";/g' src/Shared/Constants.cs
    
    - name: Change base url
      run: sed -i 's/http:\/\/127.0.0.1:5050/https:\/\/vladislavantonyuk.github.io/g' release/wwwroot/**/**.html
    
    - name: Generate RSS and Sitemap
      run: |
        dotnet build src/FileGenerator/FileGenerator.csproj -c Release -o file-generator
        dotnet file-generator/FileGenerator.dll "/release"
        cp rss.xml release/wwwroot/rss.xml
        cp sitemap.xml release/wwwroot/sitemap.xml
      
    - name: Commit wwwroot to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch : gh-pages
        publish_dir: release/wwwroot
        enable_jekyll: false
        keep_files: false
        force_orphan: true