name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    
    - name: Change constants
      run: sed -i 's/public const string BaseUrl = "\/";/public const string BaseUrl = "https:\/\/vladislavantonyuk.github.io\/";/g' src/Shared/Constants.cs
      
    - name: Update version
      run: sed -i 's/CACHE_VERSION_VALUE/${{ github.run_id }}/g' src/VladislavAntonyuk/wwwroot/service-worker.published.js
      
    - name: Publish .NET Project
      run: dotnet publish src/VladislavAntonyuk/VladislavAntonyuk.csproj -c Release -o release --nologo
      
    - name: Generate RSS and Sitemap
      run: |
        dotnet build src/FileGenerator/FileGenerator.csproj -c Release -o file-generator
        dotnet file-generator/FileGenerator.dll "/release"
        cp rss.xml release/wwwroot/rss.xml
        cp sitemap.xml release/wwwroot/sitemap.xml
        
    # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to vladislavantonyuk.github.io
      run: sed -i 's/<base href="\/"\/>/<base href="\/vladislavantonyuk.github.io\/" \/>/g' release/wwwroot/index.html
      
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch : gh-pages
        folder: release/wwwroot
